server:
  port: 8080
springdoc:
  api-docs.path: /api-docs
  swagger-ui:
    path: /api-docs-ui
spring:
  kafka:
    producer:
      bootstrap-servers: broker:9092
  datasource:
    url: jdbc:postgresql://postgres:5432/receier_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

# blobStorage type grpc or dummy
blobStorageType: grpc

# infoStorageType type jdbc or dummy
infoStorageType: jdbc

# sagaSenderType type kafka or dummy
sagaSenderType: kafka


receiver:
  kafka-wait-timeout: 1s
  next-topic: to_generator_topic
  xml-file-name: xml
  cache-refresh-timeout: 10s