server:
  port: 8080

serviceId: gateway

spring:
  cloud:
    gateway:
      routes:
        - id: xmlRoute
          uri: http://receiver:8080
          predicates:
            - Path=/receive
          filters:
            - name: TraceID
              args:
                serviceId: ${serviceId}
            - RewritePath=/receive,/v1/api
