server:
  port: 8080

serviceId: gateway

spring:
  data:
    redis:
      host: redis
      port: 6379
  application:
    name: ${serviceId}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: xmlRoute
              uri: http://receiver:8081
              predicates:
                - Path=/receive
              filters:
                - name: RequestRateLimiter
                  args:
                    # rpm 60/per minute
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 60
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@keyResolver}"
                - name: CacheRequestBody
                  args:
                    bodyClass: byte[]
                - name: ValidateInputXML
                  args:
                    acceptable: 123456789
                - name: RequestIDGenerator
                  args:
                    serviceId: ${serviceId}
                - RewritePath=/receive,/v1/api
                - name: CircuitBreaker
                  args:
                    name: backendA
                    statusCodes:
                      - 500

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-type: time_based  # timed control type
      failure-rate-threshold: 50
      sliding-window-size: 10
      wait-duration-in-open-state: 1s
      permitted-number-of-calls-in-half-open-state: 1
      minimum-number-of-calls: 5
  instances:
    backendA:
      baseConfig: default

management:
  server:
    port: 7000
  endpoint:
    prometheus:
      #  fullacces by default; (see hasRole('ROLE_ADMIN'), authenticated)
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging:
  level:
    root: INFO
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: true